USE QUANLYQUANBIDA

-- 1
-- Create the ACCESS_TBL table
CREATE TABLE ACCESS_TBL (
    IDACCESS INT PRIMARY KEY,
    NAMEACCESS VARCHAR(50)
);

-- 2
-- Create table staffs
CREATE TABLE STAFFS(
	IDSTAFF VARCHAR(10) PRIMARY KEY,
	ACCOUNT VARCHAR(50) UNIQUE,
	NAMESTAFF NVARCHAR(255),
	PHONENUM VARCHAR(10),
	POSITION NVARCHAR(50),
)

-- 3
-- Customer vip
create table VIPCUSTOMERS(
	PHONENUM varchar(10) primary key,
	NAMECUS nvarchar(255),
	POINTS int default 0
)

-- 4
-- Create shift of staff
CREATE TABLE SHIFTS(
	IDSHIFT VARCHAR(10) PRIMARY KEY,
	MONTHSHIFT INT,
	WEEKSHIFT INT,
	IDSTAFF VARCHAR(10) NULL,
	TIMELINE DATE,
	SHIFTT INT
)

-- 5
-- Create the USERS_TBL table
CREATE TABLE USERS_TBL (
    ACCOUNT VARCHAR(50) PRIMARY KEY,
    PASS VARCHAR(50),
    IDACCESS INT,
    CONSTRAINT FK_IDACCESS_USER_TBL FOREIGN KEY (IDACCESS) REFERENCES ACCESS_TBL(IDACCESS),
	CONSTRAINT FK_ACCOUNT_USER_TBL FOREIGN KEY (ACCOUNT) REFERENCES STAFFS(ACCOUNT)
);

-- 6
-- create table bida
CREATE TABLE BILLARDTABLE(
	IDTABLE VARCHAR(10) PRIMARY KEY,
	CLASSIFY VARCHAR(20),
	PRICE FLOAT,
	SITUATION VARCHAR(20) default 'Empty'
)

--7
-- Create đặt bàn
CREATE TABLE SETTABLE(
	IDTABLE VARCHAR(10) PRIMARY KEY,
	IDSTAFF VARCHAR(10),
	TIMESTART DATETIME,
	TIMEEND DATETIME NULL,
	PHONENUM VARCHAR(10),
	CONSTRAINT FK_IDTABLE_SET FOREIGN KEY (IDTABLE) REFERENCES BILLARDTABLE(IDTABLE)
);

-- 8
--create TABLE BILL
CREATE TABLE BILL(
	ID INT PRIMARY KEY,
	IDSTAFF VARCHAR(10),
	PRINTDATE DATETIME,
	FOREIGN KEY (IDSTAFF) REFERENCES STAFFS(IDSTAFF),
)

-- 9
-- Chi tiet hoa don
CREATE TABLE DETAILBILL (
    ID INT PRIMARY KEY,
    IDTABLE VARCHAR(10),
    BEGINAT DATETIME,
    FINISHAT DATETIME,
    PRICE FLOAT,
    PHONENUM VARCHAR(10) NULL,
    NAMECUS NVARCHAR(255) NULL,
    FOREIGN KEY (IDTABLE) REFERENCES BILLARDTABLE(IDTABLE)
);
